@startuml
'https://plantuml.com/class-diagram
skinparam linetype ortho

class Client
interface ClientInterface as "Client Interface"{
+method(data)
}
class Adapter{
- adaptee: Service
+method(xml)
}
class Service{
+method(JSON)
}

Client -right-> ClientInterface
ClientInterface -down-> Adapter
Adapter -right-> Service

@enduml